### ISSUE TITLE
Websocket SSL Termination

### ISSUE THREAD

**Issue by sabrehagen** [nicokaiser/nginx-websocket-proxy#1]
Hi,

I'm using nginx with node.js to offload SSL termination to nginx as node performs poorly at this. I now want to add SSL termination offloading for websockets. Does your [wss config](https://github.com/nicokaiser/nginx-websocket-proxy/blob/master/simple-wss.conf) make nginx act as an SSL termination proxy? Does it pass the websocket data on to the upstream server over ws, not wss?

Thanks!

**Comment by nicokaiser** [comment]
Yes, this code snipped should exactly do this.
