### ISSUE TITLE
Websocket connection disconnects after 4 minutes.

### ISSUE THREAD

**Issue by singhvikram704** [nicokaiser/nginx-websocket-proxy#2]
Hi, 

I configured nginx-websocket-proxy from link below:

LInk: https://github.com/nicokaiser/nginx-websocket-proxy/blob/df67cd92f71bfcb513b343beaa89cb33ab09fb05/simple-wss.conf

However, i am facing timeout issue.

Please suggest me the solution for this problem.

**Comment by nicokaiser** [comment]
How do these timeouts appear? Did you try connecting to nginx from the same server? (Just to make sure this is not a connection problem)

**Comment by nicokaiser** [comment]
And, does this also appear when using the "simple-ws.conf" configuration? This should behave alike...

**Comment by shubhamsharma1993** [comment]
Hello nicokasier,

Below is the attached file inside folder /etc/nginx/sites-enabled/test , i am using...
And my webSocket connection breaks after 3-4 minutes . Can you please help me out in this.


server {

    listen 443;

    #host name to respond to
    server_name ****.com;
    # your SSL configuration
    ssl on;
    ssl_certificate /etc/letsencrypt/live/****.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/****.com/privkey.pem;

    location / {

        # redirect all HTTP traffic to localhost:8080
        proxy_pass https://localhost:8443;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 86400s;
        proxy_read_timeout 86400s;
        keepalive_timeout  0;
        # WebSocket support (nginx 1.4)
        proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
    }

**Comment by nicokaiser** [comment]
Sorry, I cannot reproduce this.
